server:
  port: 8080
  servlet:
    context-path: /chapter02
  tomcat:
    uri-encoding: utf-8

my:
  users:
    - name: 江南一点雨
      address: China
      favorites:
        - 足球
        - 徒步
        - coding
    - name: 江南一点雨2
      address: Chin2a
      favorites:
        - 足球
        - 徒步
        - coding

